### ISSUE TITLE
Indicate code list

### ISSUE THREAD

**Issue by jakubklimek** [sstenchlak/schema-generator#35]
Like this:
![image](https://user-images.githubusercontent.com/718827/141987314-e1fc198d-793f-43b7-8fdc-90593cf0131b.png)
- icon "list"
- color like any other property
- no hierarchy

It could also be postfixed with "Code list item/Položka číselníku" type, to make it consistent with datatyped properties

**Comment by sstenchlak** [comment]
Implemented in 3f79aca6b33f2b2b50d04901992d83afc28a2c8e
