### ISSUE TITLE
Update local deployment instructions + link to online deployment

### ISSUE THREAD

**Issue by jakubklimek** [sstenchlak/schema-generator#7]
Currently, I was unable to deploy the app locally. After clone, according to README.md, I ran `yarn start`, which resulted in error with missing `react-scripts`.
I ran `npm ci` (not in instructions), then `yarn start` - something did run, but the app failed on missing `model-driven-data`.

Therefore, the local deployment instructions should be updated so that anyone is able to deploy the app.

In addition, the link https://kodi-schema-generator.netlify.app/ should be added to the repository information, so that it can be easily found.

**Comment by sstenchlak** [comment]
Thank you for waiting. I have updated the build instructions.
